runtime: python311

entrypoint: gunicorn django_auth.wsgi --bind :$PORT

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "django_auth.settings"
